[package]
name = "pp"
version = "1.0.0"
authors = ["Florian Lackner <florian.lackner@gmail.com>"]
description = """
Reads a json file and pretty prints it on stdout.
"""
license = "GNU General Public License v3.0 or later"
license-file = "LICENSE"

[dependencies]
serde_json = "1.0"
clap = "~2.31"
error-chain = "0.11"
filebuffer = "0.4.0"
